version: "3.1"
services:
  client:
    container_name: yolo_client
    restart: unless-stopped
    build: 
         context: client/
         dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - yolo_network

  backend:
    container_name: yolo_backend
    restart: unless-stopped
    build: 
         context: backend/
         dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - yolo_network
    stdin_open: true 
    depends_on:
      - mongo
      
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27018:27018
    volumes:
      - yolodata:/opt/yolo
    networks:
      - yolo_network

networks:
  yolo_network:
    driver: bridge

volumes:
  yolodata: